### ISSUE TITLE
TypeError in process_protein_cli.py

### ISSUE THREAD

**Issue by lcscs12345** [PDBeurope/arpeggio#1]
Hi Harry and Lukas,

Thank you for making arpeggio available for python 3. I got these errors for all the cif files in the test_data directory. Could you look into this?

EDIT: Just realised that -s or -sf is compulsory. Would be useful to see them optional (feature request).

```
arpeggio arpeggio/arpeggio/tests/test_data/structures/2n18.cif
```
```
INFO//02:33:51.246//Program begin.
/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 0.
  PDBConstructionWarning,
/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 0.
  PDBConstructionWarning,
/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 0.
  PDBConstructionWarning,
DEBUG//02:33:51.429//Loaded PDB structure (BioPython)
DEBUG//02:33:51.836//Loaded MMCIF structure (OpenBabel)
DEBUG//02:33:51.865//Mapped OB to BioPython atoms and vice-versa.
DEBUG//02:33:51.865//Detected that the input structure contains hydrogens. Hydrogen addition will be skipped.
Traceback (most recent call last):
  File "/nesi/nobackup/uoo00123/anaconda3/bin/arpeggio", line 6, in <module>
    main()
  File "/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 79, in main
    run_arpeggio(args)
  File "/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 90, in run_arpeggio
    selections = _parse_selection(args)
  File "/nesi/nobackup/uoo00123/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 139, in _parse_selection
    with open(args.selection_file, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by lpravda** [comment]
Hi @lcscs12345 , thank you for getting back to us with the error. I cant speak for @harryjubb, as he is the original author of arpeggio, I just made necessary changes to adopt it for PDBe needs.

Purely looking into what you have provided I suspect the reason it crashes is that you are not providing any molecular selection so that arpeggio does not know what residues should be used for contact search. I'm going to add a check at the beginning of the program sot that it crashes early if no information is provided

Thinking of the feature request, what would be the default behaviour? For now Arpeggio needs a molecular selection that is used as a source to calculate molecular interactions, if you dont provide that selection should all HET atoms be used as the selection? Including water molecules, or something else?

**Comment by harryjubb** [comment]
Hi both,

As @lpravda says, a default for a selection is tricky, particularly if you're running in bulk there may be idiosyncrasies in individual structures as to which residues / atoms are `HETATM` or not; it's usually safer to determine the interactions of interest ahead of time and be explicit.

You can provide residue names as selections (e.g. `RESNAME:FMM`), or there is a very opinionated `LIGANDS` catch-all which can be used but may not cover all edge cases.

https://github.com/PDBeurope/arpeggio/blob/57064d486c0abef96dd58f0b2b47045adc4c9b5a/arpeggio/core/utils.py#L447-L457

**Comment by lpravda** [comment]
I've been just looking into the code and if no selection is specified, it defaults to selection of all atoms in the structure. Which may be a bit overwhelming and I'm not too sure how useful this is, but anyway, I changed the selection parsing so that it no longer crashes if no selection is provided and it goes back to the default behaviour. I pushed the new branch "#1". Can you @lcscs12345 have a look if this is what you are after?

**Comment by lcscs12345** [comment]
Thank you! But it hasn't fully reverted to the default behavior (see below). I'm interested to look at the interactions between all residue-pairs. Providing a list of selections will produce redundant interactions, which I will have to filter them later on. By the way, I have written a script to do the filtering step.
```
arpeggio 2n18.cif 
```
```
INFO//11:16:00.975//Program begin.
Traceback (most recent call last):
  File "/Volumes/scratch/gardnerlab/cslim/anaconda3/bin/arpeggio", line 6, in <module>
    main()
  File "/Volumes/scratch/gardnerlab/cslim/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 79, in main
    run_arpeggio(args)
  File "/Volumes/scratch/gardnerlab/cslim/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 87, in run_arpeggio
    selections = _parse_selection(args)
  File "/Volumes/scratch/gardnerlab/cslim/anaconda3/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 138, in _parse_selection
    elif os.path.isfile(args.selection_file):
  File "/Volumes/scratch/gardnerlab/cslim/anaconda3/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by lpravda** [comment]
Hi @lcscs12345 , I fixed the typo in the code so now it no longer complains about the missing selection file, however on the protein I tried this out (some 9000 atoms) the computation just takes forever to complete, because there are a looooot of atom pairs that are in the vicinity of 5A. So you may be better of selection just certain atoms/residues per run, but give it a go and see for yourself.

Also, you may also try to restrict what 'interacting means' using '-i 3' to limit interactions in a 3A vicinity.

Let me know if this works for you

**Comment by lcscs12345** [comment]
Thanks! It doesn't seem practical to do this for all the atom pairs. More sensible for residue-pairs.

**Comment by lpravda** [comment]
I totally agree, but arpeggio is atom-based interaction profiler, so implementing this functionality would be a bit complicated in a present application design.

If you are looking into residue based distsnces you'd have to write one by yourself. I have been using this recently: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html

**Comment by harryjubb** [comment]
@lcscs12345 If you're only interested in yes/no whether residues make contact (and not interaction types), you could write something using the BioPython neighbour searching specifying `level="R"` to get pairs of residue interactions. See https://biopython.org/docs/1.74/api/Bio.PDB.NeighborSearch.html

**Comment by lcscs12345** [comment]
Thanks @harryjubb To me, contact type identification between residues is the most compelling feature of arpeggio, which is why I'm using it. I've written a script parsing the json output, which I will post it at some stage.
